export const employeesData = [
  { internalNumber: 110, employee: "Хабохов Артур" },
  { internalNumber: 111, employee: "Ященко Евгений" },
  { internalNumber: 201, employee: "Гусев Борис" },
  { internalNumber: 202, employee: "Девякович Роман" },
  { internalNumber: 203, employee: "Долгов Кирилл" },
  { internalNumber: 204, employee: "Иналов Нуралий" },
  { internalNumber: 205, employee: "Гниловский Алексей" },
  { internalNumber: 206, employee: "Абдурахманов Тимур" },
  { internalNumber: 207, employee: "Бальных Евгений" },
  { internalNumber: 208, employee: "Борзилов Александр" },
  { internalNumber: 209, employee: "Троцкова Виктория" },
  { internalNumber: 210, employee: "Ксенофонтов Никита" },
  { internalNumber: 211, employee: "Абиш-тон Никита" },
  { internalNumber: 303, employee: "Климов Роман" },
];